
/* This file is auto generated by GetGitVersion.cmake and necessary for build dependencies */

#include "version.h"

#define _SIMREEF_VERSION_ "0.1.1.3e07c7c-dirty"
#define _SIMREEF_BUILD_DATE "20250108_182337"
#define _SIMREEF_BRANCH "main"

const char *SIMREEF_VERSION = _SIMREEF_VERSION_;
const char *SIMREEF_BUILD_DATE = _SIMREEF_BUILD_DATE;
const char *SIMREEF_VERSION_DATE = _SIMREEF_VERSION_ "-" _SIMREEF_BUILD_DATE;
const char *SIMREEF_BRANCH = _SIMREEF_BRANCH;
