
// CLI11.hpp — Command Line Argument Parser
// -----------------------------------------
// This header implements the CLI11 command-line parser library, which provides
// a declarative, robust, and modern way to specify CLI options, flags, and arguments.
//
// Features:
// - Single-header and header-only
// - Supports required/optional arguments, flag grouping, and subcommands
// - Provides helpful autogenerated usage documentation
// - Supports environment variables, config files, and type-safe conversions
//
// Typical usage in SimForager:
// - Used to initialize the _options struct by parsing command-line parameters
// - Automatically maps command-line arguments to simulation settings like:
//     --dimensions 100 100 1
//     --output_dir results/
//
// Usage example:
//
// CLI::App app{"SimForager: Distributed ecological simulation"};
// app.add_option("--dimensions", opts.dimensions, "Grid dimensions")->expected(3);
// app.add_option("--output_dir", opts.output_dir, "Directory to write results");
//
// app.parse(argc, argv);
//
// For full documentation, see: https://github.com/CLIUtils/CLI11

// Note: Header is standalone; make sure it's kept up to date with upstream fixes.
